# Generated by Django 2.0 on 2017-12-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20171206_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bytelyurl',
            name='shortcode',
            field=models.CharField(blank=True, default='abc', max_length=15, unique=True),
        ),
    ]
