# Generated by Django 2.0 on 2017-12-08 13:29

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20171206_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bytelyurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url]),
        ),
    ]
