# Generated by Django 2.0 on 2017-12-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20171208_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bytelyurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
